### ISSUE TITLE
ModuleNotFoundError: No module named 'uritemplate' when running action

### ISSUE THREAD

**Issue by ferlopezm94** [benjefferies/branch-protection-bot#15]
Hi! A couple of days the [GitHub Action](https://github.com/ferlopezm94/typescript-starter/runs/745495918?check_suite_focus=true) started to fail with the following

```
2020-06-06T16:38:23.6715369Z ##[group]Run benjefferies/branch-protection-bot@1.0.2
2020-06-06T16:38:23.6715528Z with:
2020-06-06T16:38:23.6716100Z   access-token: ***
2020-06-06T16:38:23.6716225Z   enforce_admins: false
2020-06-06T16:38:23.6716359Z   branch: master
2020-06-06T16:38:23.6716474Z   retries: 5
2020-06-06T16:38:23.6716613Z ##[endgroup]
2020-06-06T16:38:23.6753506Z ##[command]/usr/bin/docker run --name d35c4cb2359e4743f799603dd827d62448_1d73a6 --label 3888d3 --workdir /github/workspace --rm -e INPUT_ACCESS-TOKEN -e INPUT_ENFORCE_ADMINS -e INPUT_OWNER -e INPUT_REPO -e INPUT_BRANCH -e INPUT_RETRIES -e ACCESS_TOKEN -e OWNER -e REPO -e BRANCH -e RETRIES -e ENFORCE_ADMINS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/typescript-starter/typescript-starter":"/github/workspace" 3888d3:5c4cb2359e4743f799603dd827d62448
2020-06-06T16:38:37.1376617Z Traceback (most recent call last):
2020-06-06T16:38:37.1378091Z   File "/bin/run.py", line 6, in <module>
2020-06-06T16:38:37.1386279Z     from github3 import login
2020-06-06T16:38:37.1388009Z   File "/pyroot/lib/python3.7/site-packages/github3/__init__.py", line 24, in <module>
2020-06-06T16:38:37.1388607Z     from .api import (
2020-06-06T16:38:37.1389581Z   File "/pyroot/lib/python3.7/site-packages/github3/api.py", line 13, in <module>
2020-06-06T16:38:37.1390203Z     from .github import GitHub, GitHubEnterprise
2020-06-06T16:38:37.1391157Z   File "/pyroot/lib/python3.7/site-packages/github3/github.py", line 8, in <module>
2020-06-06T16:38:37.1391683Z     import uritemplate
2020-06-06T16:38:37.1392768Z ModuleNotFoundError: No module named 'uritemplate'
```

The [GitHub workflow](https://github.com/ferlopezm94/typescript-starter/blob/master/.github/workflows/set-release-version.yml) remains unchanged since 12 days ago and it was working.

**Comment by benjefferies** [comment]
Could you try the latest release? Could be related to https://github.com/benjefferies/branch-protection-bot/issues/11

**Comment by ferlopezm94** [comment]
@benjefferies updating to 1.0.4 worked, thanks!
